### ISSUE TITLE
feat: Correction in Design or ReImagine commute Cards in home page

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#102]
### Description

<img src="https://user-images.githubusercontent.com/103348863/193504817-fcb27746-c33b-4984-ab09-00e335716a48.jpg" width="200px">

### Redesign the bottom section (the four cards).
for screen width >900px 3 cards are in a row and the 4th card is in a new row below it. The 4th card is looking out of place. It should be 2 cards in each row

--------------------------------------- 
Use MUI Grids component only

**Comment by ashuvssut** [comment]
@adi-uchiha you can assign this issue to yourself if you are interested.

Use MUI Grids component

**Comment by Volley-Freak** [comment]
Hey @ashuvssut can you assign this to me? I can fix that.

**Comment by ashuvssut** [comment]
@Volley-Freak  Use MUI Grids component only

**Comment by Volley-Freak** [comment]
okay will keep that in mind

**Comment by Volley-Freak** [comment]
Hey @ashuvssut i've made the PR please have a look.

**Comment by adi-uchiha** [comment]
> Hey @ashuvssut i've made the PR please have a look.

Make sure you mention the issue number in your PR description 
Example  "#45" not necessary but PR will appear here.

**Comment by Volley-Freak** [comment]
> > Hey @ashuvssut i've made the PR please have a look.
> 
> Make sure you mention the issue number in your PR description Example "#45" not necessary but PR will appear here.



> > Hey @ashuvssut i've made the PR please have a look.
> 
> Make sure you mention the issue number in your PR description Example "#45" not necessary but PR will appear here.

Thanks for helping me out @adi-uchiha

**Comment by ashuvssut** [comment]
@Volley-Freak, in order to link you PR to a certain issue, you have to use the issue's. In your case its 102. so in your PR description you should mention closes #102 or fixes #102 to link your PR to this Issue. @adi-uchiha is saying this thing only

Kindly please go through contributing.md once to learn about all these stuff. great efforts have been given by the community to write that contributing.md help guide fo you guys. Kindly go through that before creating issues/ PRs

**Comment by Volley-Freak** [comment]
> @Volley-Freak, in order to link you PR to a certain issue, you have to use the issue's. In your case its 102. so in your PR description you should mention `closes #102` or `fixes #102` to link your PR to this Issue. @adi-uchiha is saying this same thing only
> 
> Kindly please go through contributing.md once to learn about all these stuff. great efforts have been given by the community to write that contributing.md help guide fo you guys. Kindly go through that before creating issues/ PRs

Got it now. Please have a look on my [PR](https://github.com/WalkingPal/walking-pal-web/pull/107) now and let me know if I'm wrong somewhere. Actually new to git that's why facing some problems.
