### ISSUE TITLE
bug: navbar and page flickering on page navigation 

### ISSUE THREAD

**Issue by titusjoyson** [WalkingPal/walking-pal-web#106]
### Description

On navigating using navbar webpage and navbar is flickering 
![chrome-capture-2022-9-8](https://user-images.githubusercontent.com/14018471/194703659-8f9efa54-aeed-4378-9d25-3c604b9e08fa.gif)

**Comment by Chaitanya-087** [comment]
i would like to work on this issue

**Comment by titusjoyson** [comment]
@Chaitanya-087 Its already taken

**Comment by titusjoyson** [comment]
@ashuvssut Tracking the changes here [https://github.com/WalkingPal/walking-pal-web/pull/108](https://github.com/WalkingPal/walking-pal-web/pull/108)

**Comment by ashuvssut** [comment]
attach a gif/video that shows the flickering bug that you observed.
