### ISSUE TITLE
bug: Correction in the size of cards in the company page.

### ISSUE THREAD

**Issue by Asmi-1** [WalkingPal/walking-pal-web#109]
### Description

There is a card which is smaller in size in comparison to the other cards in the company page.

![Screenshot (80)](https://user-images.githubusercontent.com/78552982/194703575-afdbe5b0-7c47-4b8e-baed-51076df0c022.png)

**Comment by Eddayavuz** [comment]
I'd like to take on this. Please assign.

**Comment by its-me-Harsh-Anand** [comment]
Hey @Asmi-1 I would like to work on this issue. Please assign me

**Comment by ashuvssut** [comment]
@Asmi-1 actually all the cards are somewhat not equal in size. They are simple images. Simple CSS properties will fix these. give them `height: 100%`, `aspect-ratio:1`, `object-fit: cover` I think this will be enough

**Comment by Asmi-1** [comment]
> @Asmi-1 actually all the cards are somewhat not equal in size. They are simple images. Simple CSS properties will fix these. give them `height: 100%`, `aspect-ratio:1`, `object-fit: cover` I think this will be enough

Yes, I have examined the code and also thought of doing same as you suggested. Thank you for your valuable solution.

**Comment by Eddayavuz** [comment]
> > @Asmi-1 actually all the cards are somewhat not equal in size. They are simple images. Simple CSS properties will fix these. give them `height: 100%`, `aspect-ratio:1`, `object-fit: cover` I think this will be enough
> 
> Yes, I have examined the code and also thought of doing same as you suggested. Thank you for your valuable solution.

I have fixed the bug by simply changing gallery0's size as that was the only one that has a different size than the others. please check: this [PR](https://github.com/WalkingPal/walking-pal-web/pull/110#issuecomment-1272302938)
