### ISSUE TITLE
feat: custom play button for YouTube player component

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#113]
### Description

You need to implement a  custom play button in youtube video player (in Home page). You have to use [play.svg](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/svg/play.svg) for this

refer this [stackoverflow post](https://stackoverflow.com/q/69132970/12872199) for hints

------
### Technical Details

**Hint:** in Home.tsx, you have to work on the `playIcon` prop of `ReactPlayer` component
```jsx
<ReactPlayer
  //...
  playIcon={<Play />} 
  //...
/>
```

**Comment by pwnb0y** [comment]
assign to me I would like to work on it

**Comment by ashuvssut** [comment]
Hi @pwnb0y! Any progress update?

**Comment by ashuvssut** [comment]
Clearing assignment due to inactivity.
