### ISSUE TITLE
feat: The Nav Dropdown should appear when hovered instead of clicking

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#114]
### Description

In this case, that dropdown menu should appear when hovered on "company" button. Currently that menu only appears only when clicked on "company" button
![image](https://user-images.githubusercontent.com/60546840/194724738-dc25a902-8011-4000-81e3-6ba291070e43.png)

**Comment by parinzee** [comment]
Hello there! I can work on this. Could you please assign it to me?
