### ISSUE TITLE
bug: need accessibility improvements

### ISSUE THREAD

**Issue by satnaing** [WalkingPal/walking-pal-web#123]
### Description

The accessibility of this site can be improved. For example, there is
- the lack of lang attribute in html element
- link icons don't have alt text / title
- headings are not correctly ordered (sequentially-descending order)
- Color contrast issues
- Empty links
- etc etc
- make sure to do these accessibility improvements in **global components** too that are present in the page you are working on (for example `ScrollToTop` button or `Header` component)

Make a draft PR first. Your PR's build will be deployed.
You can use https://wave.webaim.org/report#/<PUT-YOUR-PR's-PREVIEW-BUILD's-URL-HERE> to do all your accessibility analysis. Do analysisi on the latest Preview build only. 

> Checkout the file changes and PR review comments [in this PR](https://github.com/WalkingPal/walking-pal-web/pull/127) to get more clear view on what changes you need to do.

> There are 5 pages. We need to do this in all 5 pages.

----------------------
### Progress

- [x] Home page (@satnaing   )
- [x] About page (@Asmi-1 )
- [x] Company page (@satnaing   )
- [x] FAQs page (@senali-d )
- [ ] Register and 404 page (@senali-d )
--------------------

⚠**Contributors who are interested, please tell beforehand that which page you are going to start working on. This will avoid clashes (possibility of 2 people working on the same page).**

**Comment by ashuvssut** [comment]
> headings are not correctly ordered (sequentially-descending order)

We have never thought of this before. We have not used headings in sequential order. We just followed what was heading was given in the [figma design board](https://www.figma.com/file/seUqjLLCz2X22Ymm6PZBe6/Website-%26-Other-Components?node-id=901%3A2897).

I don't think it can be changed without altering the figma designs too.

**Comment by ashuvssut** [comment]
@satnaing I have assigned you Home Page.

**Comment by Asmi-1** [comment]
I want work on About page

**Comment by ashuvssut** [comment]
@satnaing assigned you company page. Make sure cover all global components used in company page too

**Comment by senali-d** [comment]
[@ashuvssut](https://github.com/ashuvssut) I would love to work on FAQs Page
