### ISSUE TITLE
feat(footer): Add animation to Discord social icon

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#129]
#### Use these CSS animation Styles
Use this `cubic-bezier(.67,-1.22,.4,2.05) `
initially: `transform: rotateZ(0deg)`
onHover: `transform: rotateZ(360deg)`

**Comment by PeroHub** [comment]
Hi @ashuvssut please assign this issue to me, I will work on it. Thanks

**Comment by ashuvssut** [comment]
@PeroHub any progress update?

**Comment by PeroHub** [comment]
Yes, I'm pushing now @ashuvssut
