### ISSUE TITLE
feat: Implement Upper Footer Sections

### ISSUE THREAD

**Issue by Dexters-Hub** [WalkingPal/walking-pal-web#133]
### Description

Hi @ashuvssut 👋🏻 

What you are doing is really amazing! 💖  

I would like to contribute to the project by adding this footer section.

![Screenshot from 2022-10-11 19-47-14](https://user-images.githubusercontent.com/47777599/195117578-7a426460-58ea-482b-b50b-138917a100b1.png)

If you could assign this to me, It would be really great. Thank you :smile

**Comment by ashuvssut** [comment]
This part is already implemented. We have hidden it for reasons. Thanks for opening up the issues. You can contribute in #35 if you want!
