### ISSUE TITLE
feat: create an accurate page load progress bar

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#135]
### Description

- Make it a global component: `PageLoadProgress`
  ![Peek 2022-10-12 12-14](https://user-images.githubusercontent.com/60546840/195270672-c325c8b6-c795-4c2f-bbfe-e7f1b6dfa84d.gif)

- Use MUI's [Linear progress](https://mui.com/material-ui/react-progress/#linear-determinate) with props `color="primary"`
- Get estimated page load time to display load progress using Navigation Timing API. Read [this article](https://codepen.io/ahsanrathore/post/accurate-page-progress-bar) for reference

**Comment by Dexters-Hub** [comment]
Can I work on this? @ashuvssut

**Comment by ashuvssut** [comment]
Hi @Dexters-Hub! Any progress update?

**Comment by Dexters-Hub** [comment]
> Hi @Dexters-Hub! Any progress update?

I'm still working on it, The reference that you have sent  (using Navigation API) is deprecated and it is having some issues.

**Comment by Manthan-Kuber** [comment]
https://www.npmjs.com/package/nextjs-progressbar
You guys can use this. It's plug and play, highly customisable too

**Comment by Dexters-Hub** [comment]
> https://www.npmjs.com/package/nextjs-progressbar You guys can use this. It's plug-and-play, highly customizable too

Thank you @Manthan-Kuber
