### ISSUE TITLE
feat: email verification in `api/early-users` (server side)

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#137]
### Description

Create a common utility funtion in `api/utils` that can check and verify emails. If email is invalid, it will return an error response to the client-side (frontend)

**Please suggest some good ideas to implement this feature.**

--------------------
I am thinking to use [this API](https://rapidapi.com/srgl/api/validect-email-verification/pricing) to achieve this
But there is a daily quota limit which is an obvious disadvantage of using it
- So when quota limit reaches we will have to check for `HTTP error 429, Too Many Requests` to return an error response "Please try again later" to the user

**Comment by tanishq-singh-2301** [comment]
Hey @ashuvssut, can I work on this?

**Comment by ashuvssut** [comment]
Ya sure

**Comment by tanishq-singh-2301** [comment]
<b>

We can also use this [_deep-email-validator_](https://github.com/mfbx9da4/deep-email-validator).
It checks everything!!

Any thoughts? @ashuvssut 
</b>

**Comment by ashuvssut** [comment]
yes seems fine, please go ahead with that
