### ISSUE TITLE
bug: docs assets like images are not loading when viewed on GitHub Website

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#143]
### Description

![image](https://user-images.githubusercontent.com/60546840/195759096-4bb521d5-d5bb-4715-8033-780da515cacc.png)

**Comment by ashuvssut** [comment]
If this is a issue with GitHub itself, then maybe we should host these docs using docusaurus

Try to find a fix, else, we will have to use docusaurus

**Comment by DarkSoul26** [comment]
@ashuvssut I would like to work on this issue

**Comment by DarkSoul26** [comment]
Looking after the issue, I think its not issue in the code but in the GitHub. Its not loading for you maybe. Try opening on other browser once.

**Comment by ashuvssut** [comment]
> Try opening on other browser once.

done that before. no luck

**Comment by ashuvssut** [comment]
Changing network fixed it for me. I think it was a problem with my network. 

----------------
You can open a new issue if you want to work on Docusaurus

```sh
# Current Documentation Structure

README.md 
├── CODE-OF-CONDUCT.md
└── CONTRIBUTING.md
    ├── STYLE-GUIDE.md
    │   ├── TYPE-SYSTEM.md
    │   └── COLOR-SYSTEM.md
    ├── PROJECT-STRUCTURE.md
    └── GIT-GUIDELINES.md
```
