### ISSUE TITLE
feat: Create a monotone variant of our original svg logo

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#144]
### Description

we need a monotone variant of our [original svg logo](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/svg/logo.svg) (just black outlines/fills whatever you find suitable)

We will be using that svg for our app's notification icon. So that svg needs to look okay for a **very small size**. You can do it in your way that you think suits best for a small icon.

![image](https://user-images.githubusercontent.com/60546840/195761295-98af4da5-d00e-4f1d-bd97-845aaaa6b550.png)

**Comment by ashuvssut** [comment]
@annalbirena

**Comment by annalbirena** [comment]
I'll work on this
