### ISSUE TITLE
feat: Global Component - "Ready to Get started" section

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#151]
![image](https://user-images.githubusercontent.com/60546840/195082358-0b540802-a2f4-43bc-99f6-00111a8baa24.png)

**Comment by iRepo** [comment]
I think I can't

**Comment by ashuvssut** [comment]
@iRepo any progress update?

**Comment by senali-d** [comment]
@ashuvssut I think I didn't have permission to self assign task. Please assign me to the issue.
