### ISSUE TITLE
chore: Refactor scroll-to-top button

### ISSUE THREAD

**Issue by Olaleye-Blessing** [WalkingPal/walking-pal-web#152]
### Description

It seems like the [scroll-to-top](https://github.com/WalkingPal/walking-pal-web/tree/dev/components/ScrollToTop) button is being used on every page in the UI and it is repeated in every page file. I think it's better to have it in the [App file](https://github.com/WalkingPal/walking-pal-web/blob/dev/pages/_app.pg.tsx) instead of repeating it in every page file.

**Comment by BobinMathew** [comment]
Hi, can I work on this issue?

**Comment by ashuvssut** [comment]
@BobinMathew We are conditionally rendering Header and Footer components in app.pg.tsx.

Likewise I want you to do the same for scrollToTop button.

**Comment by Olaleye-Blessing** [comment]
Yea, I've dropped my comment.
