### ISSUE TITLE
Start the Youtube Video in home page only when it appears inside viewport

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#21]
In home page, the YT video starts up when the page loads. this is not desired

use [JS intersection observers](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to detect when the youtube video appears inside the viewport. when the youtube video appears inside viewport, trigger/start playing the video

Use can use this package https://www.npmjs.com/package/react-intersection-observer
or create you own custom react hook

**Comment by utsav82** [comment]
I am interested on working in this ,can I be assigned to it? @ashuvssut

**Comment by ashuvssut** [comment]
Make sure you go through the [Contributing Guidelines](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md)

**Comment by AbhishekTiwari23** [comment]
I am also interested. If it is pending, then I would like to work on it
