### ISSUE TITLE
feat: company page hero section

### ISSUE THREAD

**Issue by Im-Kunal-13** [WalkingPal/walking-pal-web#22]
![image](https://user-images.githubusercontent.com/89394181/193289494-8af863e7-3ec7-497d-885d-2920351aecfd.png)

**Comment by ashuvssut** [comment]
make sure you follow [Contributing Guidelines](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md)

To be clear You just need to create the Heading + the image Carousel
![image](https://user-images.githubusercontent.com/60546840/193290538-77346173-d301-4a6a-826e-d75ae0bcb2ff.png)

**Comment by ashuvssut** [comment]
@Im-Kunal-13 use [Swiperjs](https://swiperjs.com/react) for the carousel. set autoPlay prop. There is a `loop` config too, it makes the swiper carousel slides look like they are never ending.

**Comment by Im-Kunal-13** [comment]
> e [Swiperjs](https://swiperjs.com/react) for the carousel. set autoPlay prop. There is a `loop` config too, it makes th

On it
