### ISSUE TITLE
chore: add templates for easy maintaining

### ISSUE THREAD

**Issue by Dun-sin** [WalkingPal/walking-pal-web#24]
I saw this project is open to contributions, and it doesn't have Pull request and issue templates, it makes it easier for you to maintain your projects.

Here are links for reference: 
[Pull Request Template](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
[Pull Request and Issue Template](https://bakingclouds.com/multiple-template-choices/)

I can work on this if you want it

**Comment by ashuvssut** [comment]
ya sure go ahead. 

We have already mentioned all those points for [Issue](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md#make-sure-to-follow-these-when-opening-issues) and [PR template](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md#pull-requests-review-criteria) in Contributing.md

So, You dont need to add those checkboxes that are in your referenced links.
just add one checkbox that says `- [] I have read and I am following [the guide for creating a new <issue/PR>](put link here that I have given above)`

that's all.

you can add this line in the end of the PR template:- fixes/closes#issue_id

Also, It would be nice if you could check for spelling typos and grammar errors throughout those 8 markdown files. (you can make another issue for this if you want)
