### ISSUE TITLE
feat: social icon hover effect

### ISSUE THREAD

**Issue by AbhishekTiwari23** [WalkingPal/walking-pal-web#25]
Hello, everything is fantastic on the web, But it can be much better if we add some CSS effects. One is the hover effect on the social icons at the page's footer. 
If you find it valuable then, please assign it to me. So that I can achieve my first PR for hacktoberfest.

**Comment by ashuvssut** [comment]
use socail icons from https://react.useanimations.com/

**Comment by AbhishekTiwari23** [comment]
Thanks, I will respond as early as I can.

**Comment by ashuvssut** [comment]
@AbhishekTiwari23 can you add the discord invite link too? The invite link is in Readme.md

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23 can you add the discord invite link too? The invite link is in Readme.md
ok, I will work on that

**Comment by AbhishekTiwari23** [comment]
Hello @ashuvssut, I edited the file and added the discord icon and link. 
<img width="302" alt="Screenshot 2022-10-04 at 3 08 53 AM" src="https://user-images.githubusercontent.com/97469132/193690599-b00169ff-f8d8-4d92-8bc2-2c270863f871.png">

But I am not able put the hover effect as it is a typescript project. If you find it relevant, then please let me know. And please guide for hover effect as I googled it but did not found any good content, and also I encountered typescript first time

**Comment by ashuvssut** [comment]
https://react.useanimations.com/ these icons already have that hover animation inbuilt. You can take your time, and learn how to use external libs/ packages

**Comment by ashuvssut** [comment]
Also, TS is no different than JS. If you know JS, then this should be a piece of cake. If you need help follow discord. see Readme.md for link

**Comment by ashuvssut** [comment]
@AbhishekTiwari23 If you are working on this then please put a draft PR so that we can see your progress and help you out.

In case, if you are not working on the PR then we should reassign this issue to other new contributors

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23 If you are working on this then please put a draft PR so that we can see your progress and help you out.
> 
> In case, if you are not working on the PR then we should reassign this issue to other new contributors

Hello @ashuvssut, I apologise for replying late but college has started and I am getting less time for all this stuff. Please give me 24hr so that I can give a positive response

**Comment by ashuvssut** [comment]
@AbhishekTiwari23 If you are working on this then please put a draft PR so that we can see your progress and help you out.

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23 If you are working on this then please make your initial changes and put a draft PR so that we can see your progress and help you out.

Thanks, @ashuvssut, I will make a pr soon
