### ISSUE TITLE
create the WalkingPal logo in SVG

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#31]
Currently we have the The walkingpal logo in [PNG](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/svg/logo.svg) 
UI/UX design contributors are welcome to work on this. We need the exact same logo in SVG. 

If you could submit the logo's original Project file (.ai or .fig or whatever) along with the svg, it would be super!

**Comment by heisdinesh** [comment]
can i work on this  issue @ashuvssut
