### ISSUE TITLE
Discussion: Opportunity to create issues to Add UI features 

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#35]
This is the link to the [figma design board](https://www.figma.com/file/seUqjLLCz2X22Ymm6PZBe6/Website-%26-Other-Components?node-id=901%3A2897)

There are a lot of components that needs to be created. See the figma designs to figure out which components are needed to be done. You can **create issues to complete _one section/component_ at a time**. You can start from any page you want. You can work on max 2 issues simultaneously

--------------------

Pending compenents
- [x] #151 (@senali-d )
   ![image](https://user-images.githubusercontent.com/60546840/195082358-0b540802-a2f4-43bc-99f6-00111a8baa24.png) 
- [x] Company page - Career Opportunities (assigned @PeroHub)
- [x] Company page - Meet The Team (assigned @PeroHub)

> We are not planning to add components in Support & Blog Page.

> Suggestions for new useful components is welcome!

**Comment by PeroHub** [comment]
I have looked through the figma board and I really love what you are building. I noticed that the blog and company designs is yet to be implemented. Can I create two issues on this and proceed working? @ashuvssut

**Comment by ashuvssut** [comment]
Yes you can work on Career opportunities section in company page. Open up a separate issue
![image](https://user-images.githubusercontent.com/60546840/195081062-be202ffe-6a2f-4219-b594-e7157a931c90.png)


We are not planning to implement any more section in Blog page

**Comment by PeroHub** [comment]
Alright, I'll do that now

**Comment by PeroHub** [comment]
I will implement  Meet The Team section since it's on the same page @ashuvssut

**Comment by iRepo** [comment]
Hi @ashuvssut I would get the "Ready to get Started" section if you dont mind

**Comment by senali-d** [comment]
@ashuvssut,
I would love to work on following component. If it is not assigned yet.
![rtgs](https://user-images.githubusercontent.com/52546856/198080985-ed22bc4d-a68e-437b-8368-fcc7d3541b6a.png)

**Comment by ashuvssut** [comment]
@sonali-d checkout issue #151

**Comment by iRepo** [comment]
Hi! I'm on vacation so reassign it if you want

**Comment by ashuvssut** [comment]
@senali-d you may self-assign the issue to yourself. Else just make a random comment so that I can assign it to you
