### ISSUE TITLE
refactor: check capitalization

### ISSUE THREAD

**Issue by dejmedus** [WalkingPal/walking-pal-web#38]
### Description

Hi there, I noticed a few capitalization mismatches that I could help out with.

For example:
* walkingpal should be WalkingPal
* Fun. and Chill. > Fun and chill
* on the go. anytime, anywhere! > on the go. Anytime, anywhere!
* approved I'd > approved ID
* android > Android

Also a few minor typos:
* error occured > error occurred
* New frienships > New friendships
* news letter > newsletter
* our's > ours
* Our mission is to change the people cover... > Our mission is to change the way people cover...

If the above changes seem fine I can send over a PR for you to look at.

### Screenshots

<img width="1248" alt="WalkingPal" src="https://user-images.githubusercontent.com/59973863/193430272-ca29cd1a-88bb-4cbc-8c5e-66c12dfd7ac7.png">

**Comment by ashuvssut** [comment]
great! go ahead. also you can create another issue if you find any typos or grammatical errors in markdown docs  (see Readme.md and .docs/ folder)
