### ISSUE TITLE
feature: blog list section (Blog page)

### ISSUE THREAD

**Issue by aadilkhalifa** [WalkingPal/walking-pal-web#43]
### Description

Hi. I'd like to work on the blog page.

**Comment by ashuvssut** [comment]
pick your component. just dont pick hero section (see #29 )

**Comment by aadilkhalifa** [comment]
Hi.

I've worked on the list of blog cards on the blog page. 
[Link to PR](https://github.com/WalkingPal/walking-pal-web/pull/79)

Open to any feedback.
