### ISSUE TITLE
bug: SVG Logo

### ISSUE THREAD

**Issue by Pratham-Mishra178** [WalkingPal/walking-pal-web#45]
### Description

There is a bug in the navbar, The SVG logo is not properly placed.

### Screenshots

![Screenshot (627)](https://user-images.githubusercontent.com/78583437/193444988-e53c5bda-c741-46fe-9774-30197ec920fb.png)

**Comment by ashuvssut** [comment]
same issue exists in footer also. make sure to check all components where the svg logo is used and fix those also. I think you just need to add a width to the svg component

**Comment by Pratham-Mishra178** [comment]
> same issue exists in footer also. make sure to check all components where the svg logo is used and fix those also. I think you just need to add a width to the svg component

Okay I am looking into it
