### ISSUE TITLE
bug: fix on navigation render

### ISSUE THREAD

**Issue by eemike07** [WalkingPal/walking-pal-web#46]
### Description

I would like to tackle the following issue for hacktoberfest:

When navigating to a new page (between Home, About, and FAQ), a "flicker" of the Walking Pal Logo appears at the top-left.
It looks like Navigation bar is "not displayed" and then "displayed" for a split second.

![bug](https://user-images.githubusercontent.com/2515617/193445487-5c776267-b921-4282-8f6e-0f9c1934e8b0.gif)

**Comment by ashuvssut** [comment]
ya, please go ahead. also it looks like your local dev branch is stale. Kindly pull new changes from `upstream/dev` and then start working
