### ISSUE TITLE
bug: glitch in UI of register page

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#47]
### Description

![image](https://user-images.githubusercontent.com/60546840/193448882-238f1206-d1b6-4622-b866-ea67731bbfd2.png)
In register page, Press `Tab` key on keyboard, this kind of UI glitch will happen. (its related to accessiblilty maybe)

**Comment by og118** [comment]
Please assign this issue to me, I would like to work on this issue
