### ISSUE TITLE
docs: check for typos and grammar issues all the markdown files

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#48]
### Description

Check for typos/ captalization and grammar issues all the markdown files. Restrucutre sentences wherever you feel if necessary (see changes of PR #81 for reference). **Keep the sentences CONCISE and SIMPLE**

There are 9 markdown files.
- one README.md file
- rest 8 markdown files are in `.docs/`

**Please do mention which one you are going to work on to avoid the possibility of 2 people working on the same markdown file.** Pick up which doc page you are gonna work on and tell me before you start working. I will update the list below

----------------------
Current Progress
- [x] COLOR-SYSTEM.md (@giftade)
- [x] TYPE-SYSTEM.md 
- [x] CONTRIBUTING.md (@dejmedus )
- [x] CODE-OF-CONDICT.md (@Asmi-1 )
- [x] GIT-GUIDELINES.md (@Asmi-1 )
- [x] PROJECT-STRUCTURE.md (@dejmedus )
- [x] PROJECT-GUIDELINES.md (@Asmi-1 )
- [ ] STYLE-GUIDE.md (@Pratham-Mishra178 )
- [x] README.md(@Asmi-1 )

**Comment by giftade** [comment]
I'd like to try this

**Comment by iatharva** [comment]
Hi, Can I work on this @ashuvssut ?

**Comment by ashuvssut** [comment]
This issue will be always open. Its for anyone who can find flaws in the docs. But, this issue will assigned on first-come, first-serve basis (*ref contributing guidelines*).

**Comment by ashuvssut** [comment]
@iatharva you can pickup other .md files

**Comment by dejmedus** [comment]
Hi, I can take a look at some unassigned docs pages when iatharva is finished

**Comment by ashuvssut** [comment]
@dejmedus go through the top issue description. only 2 pages are done. no one is working currently. assign yourself any doc page you want

**Comment by dejmedus** [comment]
Sounds good, I will work on contributing.md then

**Comment by Asmi-1** [comment]
I want to work on [CODE-OF-CONDUCT.md](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CODE-OF-CONDUCT.md)

**Comment by dejmedus** [comment]
I will look over the project-structure.md

**Comment by ashuvssut** [comment]
@dejmedus @Pratham-Mishra178 if you are interested do more PRs in this, then there are 3 more markdown files remaining (see description)

**Comment by Pratham-Mishra178** [comment]
> @dejmedus @Pratham-Mishra178 if you are interested do more PRs in this, then there are 3 more markdown files remaining (see description)

okay sure, looking into it

**Comment by Asmi-1** [comment]
I want to work on [STYLE-GUIDE.md](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/STYLE-GUIDE.md)

**Comment by Asmi-1** [comment]
I want to work on [README.md](https://github.com/WalkingPal/walking-pal-web/blob/dev/README.md)

**Comment by ashuvssut** [comment]
@Asmi-1 you can work on 2 PRs at a time.

Take PROJECT-GUIDELINES.md + README.md

**Comment by Pratham-Mishra178** [comment]
I want to work on [STYLE-GUIDE.md](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/STYLE-GUIDE.md)

**Comment by ashuvssut** [comment]
@Pratham-Mishra178 please read issue description carefully before starting.

**Comment by Pratham-Mishra178** [comment]
Ok, sure

**Comment by ashuvssut** [comment]
This issue can be reopened if you want to contribute to this issue
