### ISSUE TITLE
feat: add a `SlideIn` animation component

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#49]
### Description

Create a global component named `SlideIn`. This component will take any `ReactNode` in `children` prop. whenever that `ReactNode` enters viewport, it will come sliding-in inside the viewport. also when it exits the viewport, it will go sliding-out of the viewport

use [JS intersection observers](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to detect when the `ReactNode` appears inside the viewport. when the `ReactNode` appears inside or exits out of viewport, trigger those mentioned animation

> we need to make the trigger boundaries inside viewport smaller... about  100px from top and bottom. (maybe we use `rootMargin` property to do this... i forgot)
This will make the trigger boundaries smaller so that the sliding in effect triggers only after the ReactNode has entered 100px inside the viewport. Same goes for exiting sliding out animation too

**Comment by deepak-sreekumar** [comment]
@ashuvssut  I'd like to take a stab at this. Would you mind assigning this to me?

**Comment by deepak-sreekumar** [comment]
@ashuvssut raised [PR](https://github.com/WalkingPal/walking-pal-web/pull/85). Please review when you get a chance
