### ISSUE TITLE
feat: custom play button in youtube video

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#50]
### Description

Checkout this [PR #27 review](https://github.com/WalkingPal/walking-pal-web/pull/27#pullrequestreview-1127526975). You need to implement a  custom play button in youtube video player. You have to use [play.svg](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/svg/play.svg) for this

refer this [stackoverflow post](https://stackoverflow.com/q/69132970/12872199) for hints

**Comment by tanmay-S12** [comment]
Hey, I would like to work on it. Pls assign it to me

**Comment by ashuvssut** [comment]
Hi @tanmay-S12! If you are not working on this issue, then please update us. Else we can reassign this issue so that new contributors can come up.

If you are working on this issue, please put a Draft PR.

**Comment by tanmay-S12** [comment]
> Hi @tanmay-S12! If you are not working on this issue, then please update us. Else we can reassign this issue so that new contributors can come up.
> 
> If you are working on this issue, please put a Draft PR so that we can see your progress.

Yes, I am trying to figure out how to do it. As I am a beginner, pls provide me with some more time if possible.

**Comment by ashuvssut** [comment]
@tanmay-S12 you have been working on this for a long time (5days). Consider creating a Draft PR today so that we can look at your changes done up until now. It become possible to help out by looking at your changes

**Comment by tanmay-S12** [comment]
> @tanmay-S12 you have been working on this for a long time (5days). Consider creating a Draft PR today so that we can look at your changes done up until now. It become possible to help out by looking at your changes

I haven't done any changes yet... I am trying to understand the project.

**Comment by ashuvssut** [comment]
Okay try to make progress in 2 days

**Comment by tanmay-S12** [comment]
> Okay try to make progress in 2 days

yess

**Comment by tanmay-S12** [comment]
@ashuvssut hey, thanks for your coordination, but I am unable to do it for some reason. Thanks for giving me time and a chance...You can reassign this issue to other coordinators. Sorry for the inconvenience.
