### ISSUE TITLE
docs: add steps to setup recaptcha (optional local dev environment setup)

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#53]
### Description

Developers need to setup thier ReCaptcha local environment variable so that they dont run into these errors in `/register` and `/faq` page.

![image](https://user-images.githubusercontent.com/60546840/193450891-216e6b92-7968-4d5a-9c6d-4e8f7ad39a4f.png)

-----------------------------

update documentation( contributing.md) --- dev environment setup part. mark it as "optional setup" or maybe "additional setup"(call whatever you like)

Write the steps to setup and create thier own ReCaptcha local environment variables. (Its all about going to google's recaptcha site and doing some stuff there and creating a .local.env file locally to setup ReCaptha feature)

refer https://prateeksurana.me/blog/integrating-recaptcha-with-next/ for the steps.

**Comment by akshaaatt** [comment]
Hi @ashuvssut , I would like to take this up.
