### ISSUE TITLE
bug: fix: missing navbar

### ISSUE THREAD

**Issue by Pratham-Mishra178** [WalkingPal/walking-pal-web#65]
### Description

After navigating to the registration page, when we return to our home page we will observe that nav bar is missing.

![image](https://user-images.githubusercontent.com/78583437/193490846-192d746d-6f84-4236-a74d-b4374065ee4d.png)

### Terms

- [X] I have read and I am following [the guidelines for creating a new issue](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md#make-sure-to-follow-these-when-opening-issues)

**Comment by vancassa** [comment]
Hello, may I try working on this?

**Comment by adi-uchiha** [comment]
Can I work on this ? I have made interactive and responsive navbars before

**Comment by ashuvssut** [comment]
@Pratham-Mishra178 this issue is alread fix through my commits in #14 PR. Please update your stale local `dev` branch to see new changes
