### ISSUE TITLE
feature: improving the `reimagine your daily commute` section 

### ISSUE THREAD

**Issue by adi-uchiha** [WalkingPal/walking-pal-web#66]
<img src="https://user-images.githubusercontent.com/103348863/193504817-fcb27746-c33b-4984-ab09-00e335716a48.jpg" width="200px">

I want to redesign the bottom section (the four cards).
for screen width >900px 3 cards are in a row and the 4th card is in a new row below it. The 4th card is looking out of place. It should be 2 cards in each row

**Comment by ashuvssut** [comment]
Hi @adi-uchiha 

we have a [figma design board](https://www.figma.com/file/seUqjLLCz2X22Ymm6PZBe6/Website-%26-Other-Components?node-id=901%3A2897) that we follow. We are not planning to re desing anything. Currently this section you pointed out is incomplete. You can add the rest of the UI components by referencing the figma designs. Try to replicate the exact UI components if you can. Make sure to follow style-system, font-typeface system, and other contributing guidelines

Do tell if you are interested in adding those UI components

Alternatively, if you are a UI/UX designer, you can convert those 4 PNGs to SVGs using illustrator or whatever tool you use to create vector graphics

**Comment by ashuvssut** [comment]
> Also the images of the card are blurred. The font family is also don't match the website theme

we follow the figma designs only!

-----------------------------
> I want to make them responsive

I think that those 4 cards are fairly responsive. where did you see the issue in responsiveness. At what screen size did you see a flaw in responsiveness?

**Comment by ashuvssut** [comment]
> They are responsive but for  screen width >900px 3 cards are in a row and the 4th card is in a new row below it. 

You can work on it.
if can think of a simple fix. make 2 groups cards.  (1 grp has 2 cards)
the parent wrapping those 2 group will be a flexbox with `flexwrap:wrap`

by this you wont be using CSS grids or some wierd media queries.

If you can do that without using Grids (maybe you can follow the way I told you), please go ahead and work creating another pr linking to this same issue

**Comment by ashuvssut** [comment]
>On it...
>
>They are responsive but for screen width >900px 3 cards are in a row and the 4th card is in a new row below it. The 4th card is looking out of place (maybe just my personal preference, no issue in it) I will stick to what you said I think that those 4 cards are fairly responsive.
Tell me if I should fix that minute detail
>
> For now I will be working on converting the PNG images to SVG that will solve the blurring issue on (specially on mobile screen view) I will create a PR soon on this..

@adi-uchiha if you are going to start working on this, feel free

**Comment by ashuvssut** [comment]
Moving this issue to #102
