### ISSUE TITLE
feat(register): add an option to add the university name if they selected "other" as university name

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#68]
![image](https://user-images.githubusercontent.com/60546840/193517464-791dcd98-5a0b-4875-ad21-fdd949b3bbf8.png)

Keep the "Other" field in the Select list.
But when after "Other" option is selected, instead of displaying "other" as a text in there, put a textfield there instead to give the user an optional field to write their university name.

- do no create a text field **under the** select component. We just want one thing: when "other" is selected, a TextField should appear **in place** of that "other" text.

**Comment by VadimDez** [comment]
Could you assign this to me?

**Comment by VadimDez** [comment]
@ashuvssut Just one question - how would user switch back from "Other" to something else?

**Comment by ashuvssut** [comment]
Alright! so i just tried to modify the UI, so the you can get an idea of how things would look:
![image](https://user-images.githubusercontent.com/60546840/193548533-bd61ef85-dcc1-4cab-8ebe-4bec96dc4810.png)
```jsx
// InputField.tsx
{[
	"VSSUT",
	"VIMSAR",
	"IIM Sambalpur",
	"Sambalpur University",
	"SUIIT",
	"Other",
].map((univ, i) => {

+	if (univ === "Other") { // modifications from Line 62
+		return (
+			<MenuItem value="adfasdf">
+				<TextField value="" size="small" placeholder="Other" onClick={(e)=> e.stopPropagation()}></TextField>
+			</MenuItem>
+		);
+	}
	return (
		<MenuItem
			value={univ}
			key={"univ-" + i}
			sx={{
				color: "#767676",
				fontSize: 24,
				fontWeight: 500,
				fontFamily: "Outfit",
			}}
		>
			{univ}
		</MenuItem>
	);
})}
```

Ofcourse you should remove the outline of the of the textbox. its just a mockup of how it should look

**Comment by ashuvssut** [comment]
TextField without border will look like a normal selected menu item (loose those extra paddings too.. maybe we should use [the `InputBase`](https://mui.com/material-ui/api/input-base/) component instead of `TextField`. It has minimum amount of styles.)
![image](https://user-images.githubusercontent.com/60546840/193550826-d009b686-e648-4d5e-a3c1-85d6715d1fba.png)

**Comment by VadimDez** [comment]
@ashuvssut wouldn't it be better to use [Autocomplete component](https://mui.com/material-ui/react-autocomplete/#free-solo) and allow any arbitrary value?

**Comment by ashuvssut** [comment]
@VadimDez Nice suggestion. but, you need to style that autocomplete dropdown to look same as the current dropdown. If it possible, then you may proceed with autocomple

**Comment by ashuvssut** [comment]
Hi @VadimDez, any progress update on this?

**Comment by Im-Kunal-13** [comment]
> Hi @VadimDez, any progress update on this?

@ashuvssut It's been 7 days since this issue was opened. I can work on this if you assign to me ?

**Comment by VadimDez** [comment]
Too much stuff on my table, you can take it over

**Comment by Im-Kunal-13** [comment]
> Too much stuff on my table, you can take it over

@ashuvssut assign it to me then.
