### ISSUE TITLE
feat: animate when switching between pages

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#69]
### Description

Please do tell what kind of animation you are planning to implement. It should be short and simple

### Have you read the Guidelines to create a new Issue?

- [ ] #100

**Comment by ashuvssut** [comment]
Hi @GyanPrakashRaj ! If you are not working on this issue, then please update us. Else we can reassign this issue so that new contributors can come up.

If you are working on this issue, please put a Draft PR so that we can see your progress.

**Comment by GyanPrakashRaj** [comment]
> Hi @GyanPrakashRaj ! If you are not working on this issue, then please update us. Else we can reassign this issue so that new contributors can come up.
> 
> If you are working on this issue, please put a Draft PR so that we can see your progress.

sorry i tried but failed to animate in the present pages... sorry.. kindly assign any other contributor.
