### ISSUE TITLE
feat: autofocus on input fields 🛠

### ISSUE THREAD

**Issue by IAmTamal** [WalkingPal/walking-pal-web#74]
## Changes i'd suggest  :

- `Autofocus` on the input so that  we donot need to again click the input field to type
- I intend to make it available for all devices and all pages with inputs

## Why to bother ? 

- Using `Autofocus` is a good accessibility feature
- It provides a much premium user experience
- It would remove the pain of clicking the box again and again.

## Screenshots of the changes i am suggesting : 

![image](https://user-images.githubusercontent.com/72851613/193627293-96767d9b-cc2e-4963-ac12-6792f653f3ac.png)
![image](https://user-images.githubusercontent.com/72851613/193627382-390cbb7d-5c30-4f65-80ad-3aa1df234b95.png)

## Can i work on it  ?

**YES, i'll be glad to help an awesome Opensource project 🚀**

### Have you read the Guidelines to create a new Issue?

- [X] I have read and I am following [the guidelines for creating a new issue](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md#make-sure-to-follow-these-when-opening-issues)

**Comment by adi-uchiha** [comment]
Can I work on this ? It is a simple fix

**Comment by ashuvssut** [comment]
@IAmTamal nice suggestion!
