### ISSUE TITLE
Update ReadMe + License Changes

### ISSUE THREAD

**Issue by krupalitrivedi** [WalkingPal/walking-pal-web#78]
### Description

Hello! 

I love the concept of this project and would to contribute by improving the ReadMe a little bit! ReadMe showcases the whole project in small amount of space and can make a huge different. I could do some paraphrasing as well as structure it a little bit! Also I consider linking the License to the end of the repo! 

Thank you! I would like to work on this :)

### Have you read the Guidelines to create a new Issue?

- [X] I have read and I am following [the guidelines for creating a new issue](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md#make-sure-to-follow-these-when-opening-issues)

**Comment by ashuvssut** [comment]
Hi! we are currently not looking for changes in the documentation. If you could explain what things we are missing in the docs, it would be great! 

Also, you can help out in #48 if you want

**Comment by ashuvssut** [comment]
Closing this issue now. If you can explain what things we are missing in the docs, then we can reopen this issue
