### ISSUE TITLE
feat(UI/UX Design): convert simple PNG images to SVGs

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#82]
### Description

There are some PNGs in the webisite like these:
![image](https://user-images.githubusercontent.com/60546840/194330349-377a4a00-225e-427b-a8b0-827e4cf2af31.png)

Create PRs to convert each of these simple PNGs to SVGs (PNGs can not be convert to SVGs. You need to use tools like Adobe Illustrator, figma, etc to design these vector graphics. refer PR #32 for reference --- this PR converted the logo PNG to SVG.)

Create 1 PR for 1 PNG conversion. Multiple contributors can be assigned to this issue. 

⚠**Contributors who are interested, please tell beforehand that which PNG you are going to start working on. This will avoid clashes (possibility of 2 people working on the same PNG conversion). Provide the screenshot of the PNG image so that we can figure out which PNG you are working on**

----------------------------------

# Important points

1. Please refrain from using tools that convert PNGs to SVGs. **YOU HAVE TO DO THIS MANUALLY.**
   - Please work on this ONLY if you know how/want to learn how to create SVGs
2. **We accept 1 PNG conversion per PR.** 
   - **Example**: checkout `footstep2.svg` in this PR: #134
4. Original PNG can be found in [assets/png](https://github.com/WalkingPal/walking-pal-web/tree/dev/assets/png)

**Comment by vishesh-hue** [comment]
hi, I would like to take up this issue but I m new to this and I can convert png to svg

**Comment by ashuvssut** [comment]
@vishesh-hue You can not convert PNGs to SVGs. You have to create new SVGs using some tool (adobe illustrator, figma, etc)

**Comment by harsh3311** [comment]
I am working on this

**Comment by harsh3311** [comment]
i have done half work

**Comment by harsh3311** [comment]
wait some time

**Comment by harsh3311** [comment]
should i work on this now or you have assigned this task

**Comment by ashuvssut** [comment]
⚠**Contirbutors who are interested, please tell beforehand that which PNG you are going to start working on. This will avoid clashes. Provide the screenshot of the PNG image so that we can figure out which PNG you are working on**

**Comment by harsh3311** [comment]
I have completed the task
please tell me how would I give that in pull request

**Comment by harsh3311** [comment]
![Untitled-1](https://user-images.githubusercontent.com/111215347/194575719-3373d21f-3379-4977-9486-1d9b0f459e5e.svg)

**Comment by ashuvssut** [comment]
@harsh3311 Are you using some tools to do this? I can see the line paths that thay are not straight( lines looks like a roguh pixelated path). 

Please refrain from using such inaccurate tools. **You have to do manually.** 1 PNG conversion per PR.

Please work on this if you know how to create SVGs

**Comment by ashuvssut** [comment]
@vishesh-hue @harsh3311 kindly look into the issue description. I have updated the link to the original PNGs (in Important Points section)

**Comment by annalbirena** [comment]
Hi! I would like to work on this.

**Comment by ashuvssut** [comment]
Issue moved to #141
