### ISSUE TITLE
feat: scroll to top button

### ISSUE THREAD

**Issue by Shubhrajyoti24** [WalkingPal/walking-pal-web#84]
I want to add a button at bottom right corner which scrolls back to top of the page.

**Comment by abel-otegbola** [comment]
Can I work on this

**Comment by ashuvssut** [comment]
@Shubhrajyoti24 glad you're here! Join **Discord** in case you need any help for ur PR (see README for link)

**Comment by ashuvssut** [comment]
Also, Make this button a global component

**Comment by Shubhrajyoti24** [comment]
Will do it. Am also grateful to contribute here. @ashuvssut Thanks!

**Comment by ashuvssut** [comment]
@abel-otegbola we are always looking for such helpful global components. If you have some cool ideas like #49 or like this issue, please open up a new issue!
