### ISSUE TITLE
feat: new `SlideEach` global component

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#86]
### Description

This `SlideEach` compo is a simple wrapper that can wrap each of its child element with `SlideIn` component

## Important Technical Details

this new `SlideEach` global component will take one prop: `children` and some other props which are as same as the props of `SlideIn `component. 
> 1. `SlideIn` is another global component 
> 2. The prop types  of `SlideEach` can be extended from `ISlideIn` `interface` (see SlideIn.tsx to find this `interface`)
> 3. Refer other global component which use `extends` keyword in their props `interface`. You will get a hint about how to write props types for `SlideEach`

the `children` prop of this `SlideEach` compo will have a lots of elements (i.e `children` prop is of type `ReactNode`)

**Comment by Pratham-Mishra178** [comment]
I want to work on this issue.
