### ISSUE TITLE
feat: use Zod for TS schema validation for all api endpoints

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#89]
### Description

Checkout all api endpoints in `api/` directory.

All those api directory lack proper TS schema validation. Implement that using [zod](https://www.npmjs.com/package/zod) library.

## Reference and Resources
https://www.totaltypescript.com/tutorials/zod

**Comment by Manthan-Kuber** [comment]
Willing to take this up !

**Comment by Manthan-Kuber** [comment]
@ashuvssut Where can I find type for formData you are sending from the client side? I need a expected formData type so that I can create a zod schema accordingly.

**Comment by ashuvssut** [comment]
@Manthan-Kuber 

there are 2 `interfaces` namely `IFormData` and `Fields`. you can search for these two

OR

Do a global search across the codebase with this text: `await axios.post("/api`
you will find 2 places where you can find what `formData` is being sent from the frontend

**Comment by ashuvssut** [comment]
@Manthan-Kuber any progress update?

**Comment by Manthan-Kuber** [comment]
> @Manthan-Kuber any progress update?

I have joined discord of walking pal and had pinged you about the issue there. Lets have a vc today
