### ISSUE TITLE
docs: Coloured segments in Contributing Guidelines

### ISSUE THREAD

**Issue by Pratham-Mishra178** [WalkingPal/walking-pal-web#98]
Coloring some segments in [CONTRIBUTING.md](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md) for better understanding.

**Comment by ashuvssut** [comment]
@Pratham-Mishra178 
Only these 2 section need highlighting. Make sure to to use a simple light color that could just attract attention. Also, the content in the section should be visible and look good in both GitHub's dark and light theme

1. [Make sure to follow these when opening issues](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md#make-sure-to-follow-these-when-opening-issues)
2. [Pull request review criteria](https://github.com/WalkingPal/walking-pal-web/blob/dev/.docs/CONTRIBUTING.md#pull-request-review-criteria)

**Comment by Pratham-Mishra178** [comment]
Ok
